# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authtools', '0003_auto_20160212_0911'),
        ('donate', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('snap', models.FileField(blank=True, null=True, upload_to='Event/%Y/%m/%d')),
                ('eventtype', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_event', models.DateTimeField(default=False)),
                ('dresscode', models.BooleanField(default=False)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=400)),
                ('place', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'event',
            },
        ),
        migrations.AlterField(
            model_name='donate',
            name='docfile',
            field=models.FileField(upload_to='Donate/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='service',
            name='docfile',
            field=models.FileField(upload_to='Service/%Y/%m/%d'),
        ),
    ]
