# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160212_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=120)),
                ('docfile', models.FileField(blank=True, null=True, upload_to='Service/%Y/%m/%d')),
                ('description', models.CharField(default=False, max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('duraction', models.CharField(max_length=120)),
                ('zip_Code', models.CharField(max_length=6)),
                ('address', models.CharField(default=False, max_length=60)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_Update', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'services',
                'verbose_name': 'Service',
            },
        ),
    ]
